

spring:
  application:
    name: software-projects-management-system
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sw_projectmgt
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: tedsaasfaha@gmail.com
    password: gmail app password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
